#!/usr/bin/env bash
#
# The purpose of this script is running post-start

set -e  # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables
echo post-start > /tmp/post-start
date >> /tmp/post-start
